# -*- coding: utf-8 -*-
"""
Shared Revit SpecTypeId → human-readable label mapping.
Imported by: add_sp_family_script.py, elec_connect_script.py, new_schedule_script.py
"""

SPEC_TYPE_MAP = {
    'Acceleration': 'Acceleration', 'AirFlow': 'Air Flow',
    'AirFlowDensity': 'Air Flow Density',
    'AirFlowDividedByCoolingLoad': 'Air Flow Divided By Cooling Load',
    'AirFlowDividedByVolume': 'Air Flow Divided By Volume',
    'Angle': 'Angle', 'AngularSpeed': 'Angular Speed',
    'ApparentPower': 'Apparent Power', 'ApparentPowerDensity': 'Apparent Power Density',
    'Area': 'Area', 'AreaDividedByCoolingLoad': 'Area Divided By Cooling Load',
    'AreaDividedByHeatingLoad': 'Area Divided By Heating Load',
    'AreaForce': 'Area Force', 'AreaForceScale': 'Area Force Scale',
    'AreaSpringCoefficient': 'Area Spring Coefficient', 'BarDiameter': 'Bar Diameter',
    'Bool': 'Yes/No', 'Boolean': 'Yes/No', 'CableTraySize': 'Cable Tray Size',
    'ColorTemperature': 'Color Temperature', 'ConduitSize': 'Conduit Size',
    'CoolingLoad': 'Cooling Load', 'CoolingLoadDividedByArea': 'Cooling Load Divided By Area',
    'CoolingLoadDividedByVolume': 'Cooling Load Divided By Volume',
    'CostPerArea': 'Cost Per Area', 'CostRateEnergy': 'Cost Rate Energy',
    'CostRatePower': 'Cost Rate Power', 'CrackWidth': 'Crack Width',
    'CrossSection': 'Cross Section', 'Currency': 'Currency', 'Current': 'Current',
    'Custom': 'Custom', 'DecimalSheetLength': 'Decimal Sheet Length',
    'DemandFactor': 'Demand Factor', 'Diffusivity': 'Diffusivity',
    'Displacement': 'Displacement', 'Distance': 'Distance',
    'DuctInsulationThickness': 'Duct Insulation Thickness',
    'DuctLiningThickness': 'Duct Lining Thickness', 'DuctSize': 'Duct Size',
    'Efficacy': 'Efficacy', 'ElectricalFrequency': 'Frequency',
    'ElectricalPotential': 'Voltage', 'ElectricalPower': 'Power',
    'ElectricalPowerDensity': 'Power Density',
    'ElectricalResistivity': 'Electrical Resistivity',
    'ElectricalTemperature': 'Temperature',
    'ElectricalTemperatureDifference': 'Temperature Difference',
    'Energy': 'Energy', 'Factor': 'Factor', 'Flow': 'Flow',
    'FlowPerPower': 'Flow Per Power', 'Force': 'Force', 'ForceScale': 'Force Scale',
    'HeatCapacityPerArea': 'Heat Capacity Per Area', 'HeatGain': 'Heat Gain',
    'HeatTransferCoefficient': 'Heat Transfer Coefficient',
    'HeatingLoad': 'Heating Load',
    'HeatingLoadDividedByArea': 'Heating Load Divided By Area',
    'HeatingLoadDividedByVolume': 'Heating Load Divided By Volume',
    'HvacDensity': 'HVAC Density', 'HvacEnergy': 'HVAC Energy',
    'HvacFriction': 'HVAC Friction', 'HvacMassPerTime': 'HVAC Mass Per Time',
    'HvacPower': 'HVAC Power', 'HvacPowerDensity': 'HVAC Power Density',
    'HvacPressure': 'HVAC Pressure', 'HvacRoughness': 'HVAC Roughness',
    'HvacSlope': 'HVAC Slope', 'HvacTemperature': 'HVAC Temperature',
    'HvacTemperatureDifference': 'HVAC Temperature Difference',
    'HvacVelocity': 'HVAC Velocity', 'HvacViscosity': 'HVAC Viscosity',
    'Illuminance': 'Illuminance', 'Image': 'Image', 'Integer': 'Integer',
    'Int64': 'Integer',
    'IsothermalMoistureCapacity': 'Isothermal Moisture Capacity',
    'Length': 'Length', 'LineSpringCoefficient': 'Line Spring Coefficient',
    'LinearForce': 'Linear Force', 'LinearForceScale': 'Linear Force Scale',
    'LinearMoment': 'Linear Moment', 'LinearMomentScale': 'Linear Moment Scale',
    'Luminance': 'Luminance', 'LuminousFlux': 'Luminous Flux',
    'LuminousIntensity': 'Luminous Intensity', 'Mass': 'Mass',
    'MassDensity': 'Mass Density', 'MassPerUnitArea': 'Mass Per Unit Area',
    'MassPerUnitLength': 'Mass Per Unit Length', 'Material': 'Material',
    'Moment': 'Moment', 'MomentOfInertia': 'Moment Of Inertia',
    'MomentScale': 'Moment Scale', 'MultilineText': 'Multiline Text',
    'Number': 'Number', 'NumberOfPoles': 'Number of Poles', 'Period': 'Period',
    'Permeability': 'Permeability', 'PipeDimension': 'Pipe Dimension',
    'PipeInsulationThickness': 'Pipe Insulation Thickness',
    'PipeMassPerUnitLength': 'Pipe Mass Per Unit Length', 'PipeSize': 'Pipe Size',
    'PipingDensity': 'Piping Density', 'PipingFriction': 'Piping Friction',
    'PipingMass': 'Piping Mass', 'PipingMassPerTime': 'Piping Mass Per Time',
    'PipingPressure': 'Piping Pressure', 'PipingRoughness': 'Piping Roughness',
    'PipingSlope': 'Piping Slope', 'PipingTemperature': 'Piping Temperature',
    'PipingTemperatureDifference': 'Piping Temperature Difference',
    'PipingVelocity': 'Piping Velocity', 'PipingViscosity': 'Piping Viscosity',
    'PipingVolume': 'Piping Volume',
    'PointSpringCoefficient': 'Point Spring Coefficient',
    'PowerPerFlow': 'Power Per Flow', 'PowerPerLength': 'Power Per Length',
    'Pulsation': 'Pulsation', 'Reference': 'Reference',
    'ReinforcementArea': 'Reinforcement Area',
    'ReinforcementAreaPerUnitLength': 'Reinforcement Area Per Unit Length',
    'ReinforcementCover': 'Reinforcement Cover',
    'ReinforcementLength': 'Reinforcement Length',
    'ReinforcementSpacing': 'Reinforcement Spacing',
    'ReinforcementVolume': 'Reinforcement Volume',
    'Rotation': 'Rotation', 'RotationAngle': 'Rotation Angle',
    'RotationalLineSpringCoefficient': 'Rotational Line Spring Coefficient',
    'RotationalPointSpringCoefficient': 'Rotational Point Spring Coefficient',
    'SectionArea': 'Section Area', 'SectionDimension': 'Section Dimension',
    'SectionModulus': 'Section Modulus', 'SectionProperty': 'Section Property',
    'SheetLength': 'Sheet Length', 'SiteAngle': 'Site Angle', 'Slope': 'Slope',
    'SpecificHeat': 'Specific Heat',
    'SpecificHeatOfVaporization': 'Specific Heat Of Vaporization',
    'Speed': 'Speed', 'Stationing': 'Stationing',
    'StationingInterval': 'Stationing Interval', 'Stress': 'Stress',
    'String': 'Text', 'StructuralFrequency': 'Structural Frequency',
    'StructuralVelocity': 'Structural Velocity',
    'SurfaceAreaPerUnitLength': 'Surface Area Per Unit Length',
    'ThermalConductivity': 'Thermal Conductivity',
    'ThermalExpansionCoefficient': 'Thermal Expansion Coefficient',
    'ThermalGradientCoefficientForMoistureCapacity':
        'Thermal Gradient Coefficient For Moisture Capacity',
    'ThermalMass': 'Thermal Mass', 'ThermalResistance': 'Thermal Resistance',
    'Time': 'Time', 'UnitWeight': 'Unit Weight', 'Url': 'URL', 'Volume': 'Volume',
    'WarpingConstant': 'Warping Constant', 'Wattage': 'Wattage',
    'Weight': 'Weight', 'WeightPerUnitLength': 'Weight Per Unit Length',
    'WireDiameter': 'Wire Diameter', 'YesNo': 'Yes/No', 'Text': 'Text',
    'FamilyType': 'Family Type',
}

SPEC_PROPERTIES = list(SPEC_TYPE_MAP.keys())
